name: yd_lotto_provider
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  #StateMangement
  provider: ^4.3.3

  #http
  http: ^0.12.2

  #json
  json_annotation: ^3.1.1

  #map
  google_maps_flutter: ^1.2.0
  geocoding: ^1.0.5
  geolocator: ^6.2.1


  #util
  sleek_circular_slider: ^1.2.0+web
  bot_toast: ^3.0.0
  flutter_custom_dialog: ^1.0.20
  permission_handler: ^5.1.0+2
  dotted_decoration: ^1.2.2

  #app_launcher
  flutter_launcher_icons: ^0.8.1

  #admob
  admob_flutter: ^1.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  json_serializable: ^3.5.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/lotto_main.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/grow_up.png
    - assets/images/lotto_qrcode.png
    - assets/images/lotto_main.png

  fonts:
    - family: CookieRun
      fonts:
        - asset: assets/fonts/CookieRun-Black.ttf
          weight: 900
        - asset: assets/fonts/CookieRun-Bold.ttf
          weight: 700
        - asset: assets/fonts/CookieRun-Regular.ttf
          weight: 400


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
